services:
  app:
    image: ${DOCKERHUB_USERNAME}/crud-app:latest
    env_file:
      - ./docker/.env.production
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - app_code:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - app_code:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    env_file:
      - ./docker/.env.production
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_code:
  mysql_data:
